# This is a basic workflow to help you get started with Actions
name: My build action requiring more space
on: 
  push:

jobs:
  build:
    name: Build my artifact
    runs-on: ubuntu-latest
    steps:
      - name: Maximize build space
        uses: AdityaGarg8/remove-unwanted-software@v5
        with:
          remove-android: 'true'
          remove-dotnet: 'true'
          remove-haskell: 'true'
          remove-codeql: 'true'
          remove-docker-images: 'true'
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build
        env: 
          URL: ${{ secrets.TESTFILE_URL }}
        run: |
          curl -L $(echo "$URL" | base64 -d) | zstd -19 > bigthing.zst

      
      - name: Upload Artifact
        id: upload-step
        uses: actions/upload-artifact@v4
        with:
          name: my-release-artifact
          path: bigthing.zst
          
       - name: Print Direct Link
        # Access the 'artifact-url' output from the step above
        run: echo "Artifact URL is ${{ steps.upload-step.outputs.artifact-url }}"
